language: cpp
compiler: g++
os: linux
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost-all-dev
    - cmake

before_install:
  - pip install --user cpp-coveralls

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"  CC="gcc-4.8"; fi

script:
  - make -f Makefile.mk # gcc without Autotools
  - ./unit_tests
  #- gcov unit_tests.cpp

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'