language: cpp
compiler: g++
os:       linux
sudo:     false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost-all-dev
      - lcov

install:
  - export CXX="g++-4.8"
  - pip install --user travis requests[security] cpp-coveralls

script:
  - make -f Makefile.mk 
  - ./unit_tests

after_success:

  - coveralls -r . -b . --gcov /usr/bin/${GCOV} --repo-token "${COVERALLS_TOKEN}") --gcov-options '\-lp'

