language: cpp
compiler: g++
os:       linux
sudo:     false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost-all-dev
      - lcov

install:
  - export CXX="g++-4.8" 

script:
  - make -f Makefile.mk 
  - ./unit_tests

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --list coverage.info
  - coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info

