# version format
version: 0.{build}-{branch}

skip_tags: true

environment:
  fast_finish: true

  matrix:
  - platform: x64
    os: Previous Visual Studio 2015
    env: BS=cmake GENERATOR="MinGW Makefiles" MEMCHECK=DRMEMORY

init:
clone_folder:
before_build:
install:
  - cinst drmemory
  - appveyor DownloadFile http://downloads.sourceforge.net/mingw-w64/x86_64-5.2.0-release-posix-seh-rt_v4-rev1.7z
  - 7z x x86_64-5.2.0-release-posix-seh-rt_v4-rev1.7z > nul
  - C:\"Program Files (x86)"\"Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
  - set PATH=%PATH%;mingw64\bin

build_script:
  - mingw32-make all
after_build:
before_test:
test_script:
  ./unit_tests
after_test:
on_success:
on_failure:
on_finish: